// The 8BitScript source for a theme on one machine: consts only, so every byte
// is program-image data (AGENTS.md: const arrays are never in RAM). Laid out so a
// reel composer indexes it directly; the layout is documented in docs/tiles.md.
import { createHash } from 'node:crypto';

function array(name, type, values, comment) {
  const lines = [];
  for (let i = 0; i < values.length; i += 16) lines.push('    ' + values.slice(i, i + 16).join(', '));
  return `${comment ? `// ${comment}\n` : ''}export const ${name}: array<${type}, ${values.length}> = [\n${lines.join(',\n')}\n];\n`;
}

export function hashOf(value) {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex').slice(0, 12);
}

/** Pixel-mode file. `data` = { symbols:[{id,bitmap,colors}], cellsW, cellsH, frame:{names,bitmaps,colors}, background } */
export function emitPixels(theme, machine, data, serves) {
  const { cellsW, cellsH } = data;
  const cells = cellsW * cellsH;
  const symbolBytes = cells * 8;
  const bitmap = data.symbols.flatMap((s) => [...s.bitmap]);
  const colors = data.symbols.flatMap((s) => [...s.colors]);
  const frame = data.frame;
  const bytes = bitmap.length + colors.length + frame.bitmaps.length * 8 + frame.colors.length;
  const hash = hashOf({ theme: theme.name, machine, bitmap, colors, fb: frame.bitmaps.map((b) => [...b]), fc: frame.colors });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: ${machine}${serves ? ` (also serves ${serves})` : ''}   mode: pixels (1 bpp, one ink colour per 8x8 cell)`,
    `// Game: ${theme.game}   symbols: ${data.symbols.map((s) => s.id).join(' ')}`,
    `// ${data.symbols.length} symbols of ${cellsW}x${cellsH} cells = ${cellsW * 8}x${cellsH * 8} pixels   data ${bytes} bytes in the program image   art ${hash}`,
    '',
    `export const TILE_MODE: utinyint = 1; // 0 = quadrant screen codes (PET), 1 = pixel bitmaps with a colour per cell`,
    `export const ART_SYMBOLS: utinyint = ${data.symbols.length}; // symbols with art; equals SYMBOL_COUNT in the game's generated odds file`,
    `export const SYMBOL_CELLS_W: utinyint = ${cellsW}; // character cells across one symbol`,
    `export const SYMBOL_CELLS_H: utinyint = ${cellsH}; // character cells down one symbol`,
    `export const SYMBOL_CELLS: utinyint = ${cells};`,
    `export const SYMBOL_BYTES: usmallint = ${symbolBytes}; // bytes of SYMBOL_BITMAP per symbol (cells x 8 pixel rows)`,
    `export const BACKGROUND_COLOR: utinyint = ${data.background}; // the paper colour the art was made against: screen.setColors / the background register`,
    ...data.symbols.map((s, i) => `export const ART_${s.id}: utinyint = ${i}; // symbol index, in the engine's order`),
    '',
    array('SYMBOL_BITMAP', 'utinyint', bitmap, `[symbol * SYMBOL_BYTES + cell * 8 + pixelRow], cell = cellRow * SYMBOL_CELLS_W + cellCol, bit 7 = leftmost pixel`),
    array('SYMBOL_COLOR', 'utinyint', colors, `[symbol * SYMBOL_CELLS + cell]: ${machine}'s own colour number for that cell's ink`),
    emitFrame(frame),
  ].join('\n');
}

function emitFrame(frame) {
  const bitmap = frame.bitmaps.flatMap((b) => [...b]);
  return [
    `export const FRAME_CELLS: utinyint = ${frame.names.length}; // frame, bevel, divider and panel cells`,
    ...frame.names.map((n, i) => `export const FRAME_${n}: utinyint = ${i};`),
    '',
    array('FRAME_BITMAP', 'utinyint', bitmap, '[frameCell * 8 + pixelRow], bit 7 = leftmost pixel'),
    array('FRAME_COLOR', 'utinyint', frame.colors, '[frameCell]: the ink colour'),
  ].join('\n');
}

/** Quadrant-mode file (PET). */
export function emitQuadrants(theme, machine, data, quadCodes) {
  const { cellsW, cellsH } = data;
  const rowsPer = cellsH * 2;
  const pixels = data.symbols.flatMap((s) => [...s.rows]);
  const frame = data.frame;
  const bytes = pixels.length + 16 + frame.codes.length;
  const hash = hashOf({ theme: theme.name, machine, pixels, frame: frame.codes });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: ${machine}   mode: quadrants (the ROM's 2x2 block glyphs: ${cellsW * 2}x${rowsPer} pseudo-pixels a symbol)`,
    `// Game: ${theme.game}   symbols: ${data.symbols.map((s) => s.id).join(' ')}`,
    `// ${data.symbols.length} symbols of ${cellsW}x${cellsH} cells   data ${bytes} bytes in the program image   art ${hash}`,
    '',
    `export const TILE_MODE: utinyint = 0; // 0 = quadrant screen codes (PET), 1 = pixel bitmaps with a colour per cell`,
    `export const ART_SYMBOLS: utinyint = ${data.symbols.length}; // symbols with art; equals SYMBOL_COUNT in the game's generated odds file`,
    `export const SYMBOL_CELLS_W: utinyint = ${cellsW};`,
    `export const SYMBOL_CELLS_H: utinyint = ${cellsH};`,
    `export const SYMBOL_CELLS: utinyint = ${cellsW * cellsH};`,
    `export const SYMBOL_PIXEL_ROWS: utinyint = ${rowsPer}; // pseudo-pixel rows a symbol has (2 per cell row)`,
    `export const SYMBOL_PIXEL_COLS: utinyint = ${cellsW * 2}; // pseudo-pixels across (bit 7 is the leftmost)`,
    `export const SYMBOL_BYTES: usmallint = ${rowsPer}; // bytes of SYMBOL_PIXELS per symbol, one a pseudo-pixel row`,
    ...data.symbols.map((s, i) => `export const ART_${s.id}: utinyint = ${i}; // symbol index, in the engine's order`),
    '',
    array('QUAD_CODE', 'utinyint', quadCodes, 'screen code for a 2x2 block pattern, indexed topLeft<<3 | topRight<<2 | bottomLeft<<1 | bottomRight (from the PET character ROM; reverse video makes the upper eight)'),
    array('SYMBOL_PIXELS', 'utinyint', pixels, '[symbol * SYMBOL_PIXEL_ROWS + row]: one byte a pseudo-pixel row, bit 7 = leftmost; two rows and two columns make one cell'),
    `export const FRAME_CELLS: utinyint = ${frame.names.length}; // frame, bevel, divider and panel cells`,
    ...frame.names.map((n, i) => `export const FRAME_${n}: utinyint = ${i};`),
    '',
    array('FRAME_CODE', 'utinyint', frame.codes, '[frameCell]: the screen code to print'),
  ].join('\n');
}
