// The 8BitScript source for a theme on one machine: consts only, so every byte
// is program-image data (AGENTS.md: const arrays are never in RAM). Laid out so a
// reel composer indexes it directly; the layout is documented in docs/tiles.md.
import { createHash } from 'node:crypto';

function array(name, type, values, comment) {
  const lines = [];
  for (let i = 0; i < values.length; i += 16) lines.push('    ' + values.slice(i, i + 16).join(', '));
  return `${comment ? `// ${comment}\n` : ''}export const ${name}: array<${type}, ${values.length}> = [\n${lines.join(',\n')}\n];\n`;
}

export function hashOf(value) {
  return createHash('sha256').update(JSON.stringify(value)).digest('hex').slice(0, 12);
}

/** A row byte with its bits mirrored (the web's glyph table has bit 0 as the leftmost pixel). */
export function reverseBits(byte) {
  let out = 0;
  for (let i = 0; i < 8; i += 1) if ((byte >> i) & 1) out |= 0x80 >> i;
  return out;
}

/** Pixel-mode file. `data` = { symbols:[{id,bitmap,colors}], cellsW, cellsH, frame:{names,bitmaps,colors}, background }; `options.lsbLeft` mirrors every row byte. */
export function emitPixels(theme, machine, data, serves, options = {}) {
  const lsbLeft = options.lsbLeft === true;
  const flip = (bytes) => (lsbLeft ? bytes.map(reverseBits) : bytes);
  const { cellsW, cellsH } = data;
  const cells = cellsW * cellsH;
  const symbolBytes = cells * 8;
  const bitmap = flip(data.symbols.flatMap((s) => [...s.bitmap]));
  const colors = data.symbols.flatMap((s) => [...s.colors]);
  const frame = data.frame;
  const frameBitmap = flip(frame.bitmaps.flatMap((b) => [...b]));
  const bytes = bitmap.length + colors.length + frameBitmap.length + frame.colors.length;
  const hash = hashOf({ theme: theme.name, machine, bitmap, colors, fb: frameBitmap, fc: frame.colors });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: ${machine}${serves ? ` (also serves ${serves})` : ''}   mode: pixels (1 bpp, one ink colour per 8x8 cell, ${lsbLeft ? 'bit 0 = leftmost pixel' : 'bit 7 = leftmost pixel'})`,
    `// Game: ${theme.game}   symbols: ${data.symbols.map((s) => s.id).join(' ')}`,
    `// ${data.symbols.length} symbols of ${cellsW}x${cellsH} cells = ${cellsW * 8}x${cellsH * 8} pixels   data ${bytes} bytes in the program image   art ${hash}`,
    '',
    `export const TILE_MODE: utinyint = 1; // 0 = quadrant screen codes (PET), 1 = pixel bitmaps with a colour per cell`,
    `export const ART_SYMBOLS: utinyint = ${data.symbols.length}; // symbols with art; equals SYMBOL_COUNT in the game's generated odds file`,
    `export const SYMBOL_CELLS_W: utinyint = ${cellsW}; // character cells across one symbol`,
    `export const SYMBOL_CELLS_H: utinyint = ${cellsH}; // character cells down one symbol`,
    `export const SYMBOL_CELLS: utinyint = ${cells};`,
    `export const SYMBOL_BYTES: usmallint = ${symbolBytes}; // bytes of SYMBOL_BITMAP per symbol (cells x 8 pixel rows)`,
    `export const BIT0_IS_LEFT: bool = ${lsbLeft}; // false: bit 7 is the leftmost pixel of a row (C64, VIC-20, X16); true: bit 0 is (the web's glyph table)`,
    `export const BACKGROUND_COLOR: utinyint = ${data.background}; // the paper colour the art was made against: screen.setColors / the background register`,
    ...data.symbols.map((s, i) => `export const ART_${s.id}: utinyint = ${i}; // symbol index, in the engine's order`),
    '',
    array('SYMBOL_BITMAP', 'utinyint', bitmap, `[symbol * SYMBOL_BYTES + cell * 8 + pixelRow], cell = cellRow * SYMBOL_CELLS_W + cellCol, ${lsbLeft ? 'bit 0' : 'bit 7'} = leftmost pixel`),
    array('SYMBOL_COLOR', 'utinyint', colors, `[symbol * SYMBOL_CELLS + cell]: ${machine}'s own colour number for that cell's ink`),
    emitFrame(frame, frameBitmap, lsbLeft),
  ].join('\n');
}

function emitFrame(frame, bitmap, lsbLeft) {
  return [
    `export const FRAME_CELLS: utinyint = ${frame.names.length}; // frame, bevel, divider and panel cells`,
    ...frame.names.map((n, i) => `export const FRAME_${n}: utinyint = ${i};`),
    '',
    array('FRAME_BITMAP', 'utinyint', bitmap, `[frameCell * 8 + pixelRow], ${lsbLeft ? 'bit 0' : 'bit 7'} = leftmost pixel`),
    array('FRAME_COLOR', 'utinyint', frame.colors, '[frameCell]: the ink colour'),
  ].join('\n');
}

/** Quadrant-mode file (PET). */
export function emitQuadrants(theme, machine, data, quadCodes) {
  const { cellsW, cellsH } = data;
  const rowsPer = cellsH * 2;
  const pixels = data.symbols.flatMap((s) => [...s.rows]);
  const frame = data.frame;
  const bytes = pixels.length + 16 + frame.codes.length;
  const hash = hashOf({ theme: theme.name, machine, pixels, frame: frame.codes });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: ${machine}   mode: quadrants (the ROM's 2x2 block glyphs: ${cellsW * 2}x${rowsPer} pseudo-pixels a symbol)`,
    `// Game: ${theme.game}   symbols: ${data.symbols.map((s) => s.id).join(' ')}`,
    `// ${data.symbols.length} symbols of ${cellsW}x${cellsH} cells   data ${bytes} bytes in the program image   art ${hash}`,
    '',
    `export const TILE_MODE: utinyint = 0; // 0 = quadrant screen codes (PET), 1 = pixel bitmaps with a colour per cell`,
    `export const ART_SYMBOLS: utinyint = ${data.symbols.length}; // symbols with art; equals SYMBOL_COUNT in the game's generated odds file`,
    `export const SYMBOL_CELLS_W: utinyint = ${cellsW};`,
    `export const SYMBOL_CELLS_H: utinyint = ${cellsH};`,
    `export const SYMBOL_CELLS: utinyint = ${cellsW * cellsH};`,
    `export const SYMBOL_PIXEL_ROWS: utinyint = ${rowsPer}; // pseudo-pixel rows a symbol has (2 per cell row)`,
    `export const SYMBOL_PIXEL_COLS: utinyint = ${cellsW * 2}; // pseudo-pixels across (bit 7 is the leftmost)`,
    `export const SYMBOL_BYTES: usmallint = ${rowsPer}; // bytes of SYMBOL_PIXELS per symbol, one a pseudo-pixel row`,
    ...data.symbols.map((s, i) => `export const ART_${s.id}: utinyint = ${i}; // symbol index, in the engine's order`),
    '',
    array('QUAD_CODE', 'utinyint', quadCodes, 'screen code for a 2x2 block pattern, indexed topLeft<<3 | topRight<<2 | bottomLeft<<1 | bottomRight (from the PET character ROM; reverse video makes the upper eight)'),
    array('SYMBOL_PIXELS', 'utinyint', pixels, '[symbol * SYMBOL_PIXEL_ROWS + row]: one byte a pseudo-pixel row, bit 7 = leftmost; two rows and two columns make one cell'),
    `export const FRAME_CELLS: utinyint = ${frame.names.length}; // frame, bevel, divider and panel cells`,
    ...frame.names.map((n, i) => `export const FRAME_${n}: utinyint = ${i};`),
    '',
    array('FRAME_CODE', 'utinyint', frame.codes, '[frameCell]: the screen code to print'),
  ].join('\n');
}

/**
 * The Commander X16's sprite form of a theme: every symbol's 48x48 master as 4 bits a pixel
 * (left pixel in the high nibble, 1,152 bytes a symbol), and the sixteen-entry palette they
 * index. Index 0 is VERA's "clear"; indices 1-15 are the theme's own fifteen colours in the
 * order theme.json lists them (the first must be black: a transparent pixel of the art is stored as it), so a master drawn in them converts exactly and any other art
 * goes to the nearest of them. The reel view stands each symbol in the middle of a 64x64
 * sprite when it uploads (VERA's sprites are 8, 16, 32 or 64 wide); only the 48x48 is stored.
 */
export function emitVera(theme, nearest) {
  const names = Object.keys(theme.colors);
  if (names.length > 15) throw new Error(`theme ${theme.name}: a VERA sprite palette holds 15 colours and the clear index, the theme has ${names.length}`);
  const palette = [[0, 0, 0], ...names.map((n) => theme.colors[n])];
  const [r1, g1, b1] = palette[1];
  if (r1 + g1 + b1 !== 0) throw new Error(`theme ${theme.name}: the first colour in theme.json must be black (it is the sprites' opaque black, palette index 1), not rgb(${r1}, ${g1}, ${b1})`);
  const allowed = names.map((_, i) => i + 1);
  const SIDE = 48;
  const bytes = [];
  for (const s of theme.symbols) {
    const { width, height, rgba } = s.img;
    if (width !== SIDE || height !== SIDE) throw new Error(`theme ${theme.name}: symbol ${s.id} is ${width}x${height}; VERA sprite art is ${SIDE}x${SIDE}`);
    const pixel = (x, y) => {
      const o = (y * width + x) * 4;
      // a transparent pixel inside the art is opaque black (index 1), so the window has no holes a background effect can show through; the clear index (0) is only the margin the view adds round the art
      return rgba[o + 3] < 128 ? 1 : nearest(palette, [rgba[o], rgba[o + 1], rgba[o + 2]], allowed);
    };
    for (let y = 0; y < SIDE; y += 1) for (let x = 0; x < SIDE; x += 2) bytes.push((pixel(x, y) << 4) | pixel(x + 1, y));
  }
  const vera = [];
  for (let i = 0; i < 16; i += 1) {
    const [r, g, b] = palette[i] ?? [0, 0, 0];
    vera.push(((g >> 4) << 4) | (b >> 4), r >> 4); // VERA: GGGGBBBB, then 0000RRRR
  }
  const hash = hashOf({ theme: theme.name, bytes, vera });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: Commander X16 sprites   mode: VERA 4 bpp (left pixel in the high nibble, index 0 = clear, index 1 = opaque black)`,
    `// Game: ${theme.game}   symbols: ${theme.symbols.map((s) => s.id).join(' ')}`,
    `// ${theme.symbols.length} symbols of ${SIDE}x${SIDE} pixels = ${bytes.length} bytes in the program image   art ${hash}`,
    '',
    `export const VERA_SYMBOLS: utinyint = ${theme.symbols.length}; // symbols with art, in the engine's order`,
    `export const VERA_SIDE: utinyint = ${SIDE}; // a symbol's width and height in pixels`,
    `export const VERA_SYMBOL_BYTES: usmallint = ${(SIDE * SIDE) / 2}; // bytes of VERA_PIXELS per symbol`,
    `export const VERA_TOTAL_BYTES: usmallint = ${bytes.length};`,
    '',
    array('VERA_PALETTE', 'utinyint', vera, 'sixteen VERA palette entries, two bytes each (GB then 0R); entry 0 is the clear index'),
    array('VERA_PIXELS', 'utinyint', bytes, '[symbol * VERA_SYMBOL_BYTES + row * 24 + column / 2], row 0..47, the left pixel of a pair in the high nibble'),
  ].join('\n');
}
