// Quadrant-block reels of any size: the tables a composer reads (docs/tiles.md, "Quadrant tables").
//
// A symbol is S x S character cells, each cell a 2x2 picture from the machine's block glyphs, so
// 2S x 2S "pseudo-pixels" (S = 6: 12x12, 48x48 screen pixels). A reel scrolls one pseudo-pixel row
// (four screen pixels) at a time, and a display cell takes two consecutive rows of the window, so the
// screen code of every display cell is one of three precomputed tables and a redraw is one read and
// one write a cell:
//
//   QUAD_C0[(symbol * S + k) * S + c]           the pair starts on an even row: rows 2k and 2k+1 of the symbol
//   QUAD_C1[(symbol * (S - 1) + k) * S + c]     it starts on an odd row: rows 2k+1 and 2k+2 (k < S - 1)
//   QUAD_CX[(symbol * NSYM + next) * S + c]     the odd pair that straddles two symbols: the last row of
//                                               `symbol` over the first row of `next`
//   QUAD_K[(symbol * S + k) * S + c]            the ink of symbol cell (k, c) (a machine with colour)
//
// The tables are the only thing that knows the art: the composer (src/labs/*/quad.8bs) is the same for every
// theme, symbol size and machine that has block glyphs.
import { resample, QUAD_CODE, toPixelSymbol } from './convert.mjs';
import { hashOf } from './emit.mjs';

/** Which machines get quadrant tables, in which file, with which screen codes and colour. */
export const QUAD_OUTPUTS = [
  // The PET's block codes are the same in the VIC-20's and the C64's character ROMs; the base file serves any machine that has no twin.
  { file: (t) => `${t}.quad.8bs`, machine: 'pet', codes: QUAD_CODE, colored: false },
  { file: (t) => `${t}.quad.vic20.8bs`, machine: 'vic20', codes: QUAD_CODE, colored: true },
  // The web's host font has the sixteen blocks at codes 128-143, in the composer's own pattern order.
  { file: (t) => `${t}.quad.web.8bs`, machine: 'web', codes: Array.from({ length: 16 }, (_, i) => 128 + i), colored: true },
];

/** The pseudo-pixel bitmap of one symbol: P rows of P 0/1 values. */
export function pseudoPixels(img, S) {
  const P = 2 * S;
  const r = resample(img, P, P);
  return Array.from({ length: P }, (_, y) => Array.from({ length: P }, (_, x) => (r.cover[y * P + x] >= 0.5 ? 1 : 0)));
}

/** The tables for symbols `images` (PNG-decoded), S cells a side, as plain arrays. */
export function quadTables(images, S, codes, ink) {
  const P = 2 * S;
  const bitmaps = images.map((img) => pseudoPixels(img, S));
  const code = (a, b, c) => codes[(a[2 * c] << 3) | (a[2 * c + 1] << 2) | (b[2 * c] << 1) | b[2 * c + 1]];
  const n = images.length;
  const C0 = [], C1 = [], CX = [], K = [];
  for (let s = 0; s < n; s += 1) {
    for (let k = 0; k < S; k += 1) for (let c = 0; c < S; c += 1) C0.push(code(bitmaps[s][2 * k], bitmaps[s][2 * k + 1], c));
    for (let k = 0; k < S - 1; k += 1) for (let c = 0; c < S; c += 1) C1.push(code(bitmaps[s][2 * k + 1], bitmaps[s][2 * k + 2], c));
  }
  for (let s = 0; s < n; s += 1) for (let u = 0; u < n; u += 1) for (let c = 0; c < S; c += 1) CX.push(code(bitmaps[s][P - 1], bitmaps[u][0], c));
  if (ink) for (let s = 0; s < n; s += 1) K.push(...ink(images[s], s));
  else K.push(0);
  return { P, bitmaps, C0, C1, CX, K };
}

const array = (name, values, comment) => {
  const lines = [];
  for (let i = 0; i < values.length; i += 16) lines.push('    ' + values.slice(i, i + 16).join(', '));
  return `// ${comment}\nexport const ${name}: array<utinyint, ${values.length}> = [\n${lines.join(',\n')}\n];\n`;
};

/** The source of one quadrant-table file. `S` is the symbol size in cells for this machine. */
export function emitQuadTables(theme, out, S) {
  // The shape is the symbol hand-drawn on this size's own coarse grid (<ID>.quad<S>.png) if the theme has one, else
  // the master resampled; the ink always comes from the colour master.
  const images = theme.symbols.map((s) => s.overrides[`quad${S}`] ?? s.img);
  const masters = theme.symbols.map((s) => s.img);
  const ink = out.colored
    ? (img) => {
      const px = toPixelSymbol(img, out.machine, S, S);
      // one colour a symbol cell, in the machine's own numbers (VIC-20: 0-7, web: 0-15)
      return Array.from(px.colors, (v) => (out.machine === 'vic20' ? v & 7 : v));
    }
    : null;
  const t = quadTables(images, S, out.codes, ink && ((img, i) => ink(masters[i])));
  const n = images.length;
  const bytes = t.C0.length + t.C1.length + t.CX.length + (out.colored ? t.K.length : 0);
  const hash = hashOf({ theme: theme.name, machine: out.machine, S, C0: t.C0, C1: t.C1, CX: t.CX, K: t.K });
  return [
    `// GENERATED by tools/tiles from assets/themes/${theme.name}/ — do not edit.`,
    `// Regenerate with: node tools/tiles/bin/tiles.mjs build ${theme.name}`,
    `// Theme: ${theme.title}   machine: ${out.machine}   mode: quadrant tables (the 2x2 block glyphs: ${S}x${S} cells = ${2 * S}x${2 * S} pseudo-pixels = ${8 * S}x${8 * S} screen pixels a symbol)`,
    `// Game: ${theme.game}   symbols: ${theme.symbols.map((s) => s.id).join(' ')}`,
    `// ${n} symbols   data ${bytes} bytes in the program image   art ${hash}`,
    '',
    `export const QUAD_S: utinyint = ${S}; // cells a symbol is on a side`,
    `export const QUAD_P: utinyint = ${2 * S}; // pseudo-pixel rows a symbol has (two a cell)`,
    `export const QUAD_SYMBOLS: utinyint = ${n}; // symbols with art; equals SYMBOL_COUNT in the odds file`,
    `export const QUAD_COLORED: bool = ${out.colored}; // QUAD_K holds an ink a symbol cell`,
    '',
    array('QUAD_C0', t.C0, '[(symbol * QUAD_S + k) * QUAD_S + c]: the cell for symbol rows 2k and 2k+1 (a window that starts on an even pseudo-pixel row)'),
    array('QUAD_C1', t.C1, '[(symbol * (QUAD_S - 1) + k) * QUAD_S + c]: symbol rows 2k+1 and 2k+2 (an odd start), k < QUAD_S - 1'),
    array('QUAD_CX', t.CX, '[(symbol * QUAD_SYMBOLS + next) * QUAD_S + c]: the last row of symbol over the first row of next (the pair that straddles two symbols)'),
    array('QUAD_K', t.K, out.colored ? '[(symbol * QUAD_S + k) * QUAD_S + c]: the ink of symbol cell (k, c)' : 'unused on a machine with no colour'),
  ].join('\n');
}
