// The PAR sheet: everything a designer or a player needs to know about a game's
// odds, as markdown (for people and the repo) and JSON (for tests and tools).
import { pct, oneIn } from './util.mjs';

const num = (x, d = 3) => x.toFixed(d);

export function toJson(analysis, extras = {}) {
  return JSON.parse(JSON.stringify({ ...analysis, ...extras }, (_, v) => (typeof v === 'bigint' ? v.toString() : v === Infinity ? 'Infinity' : v)));
}

export function toMarkdown(spec, a, emitted) {
  const exact = a.method === 'exact';
  const out = [];
  out.push(`# PAR sheet - ${spec.title} (\`${spec.id}\`)`);
  out.push('');
  out.push(`> GENERATED by \`tools/slotmath\` from spec \`${spec.hash}\`. ${exact ? 'Every figure below is **exact**: computed by enumerating every reel combination (or by closed form), never sampled.' : `The line/cluster pays are a **Monte Carlo estimate** (${a.ci.samples.toLocaleString('en-US')} spins, fixed seed, 95% interval shown); scatter and bonus-symbol probabilities, and the feature maths layered on the estimate, are exact given it.`}`);
  out.push('> For entertainment simulation. This is not a regulated-lab certification.');
  out.push('');
  out.push('## Headline');
  out.push('');
  out.push('| | |');
  out.push('|---|---|');
  out.push(`| Layout | ${a.reels} reels x ${a.rows} rows, ${a.stops} stops per reel, ${spec.mode} pays |`);
  out.push(`| Outcomes per spin | ${a.outcomes.toLocaleString('en-US')} equally likely reel combinations |`);
  out.push(`| **Return to player** | **${exact ? pct(a.rtp, 4) : `${pct(a.rtp, 3)} +/- ${pct(a.ci.half, 3)}`}** at maximum bet |`);
  if (a.exactBase) out.push(`| Lines + scatter, as a fraction | ${a.exactBase.numerator} / ${a.exactBase.denominator} |`);
  out.push(`| Hit frequency (a win on the spin) | ${pct(a.hitFrequency, 3)} - 1 in ${(1 / a.hitFrequency).toFixed(2)} |`);
  if (spec.freeSpins) out.push(`| Free-spin trigger | 1 in ${oneIn(a.freeSpinTrigger)} |`);
  if (spec.bonus) out.push(`| Bonus wheel trigger | 1 in ${oneIn(a.bonusTrigger)} |`);
  out.push(`| Volatility (std dev per spin) | ${num(a.sigma)} bets |`);
  out.push(`| Largest single-spin base win | ${num(a.maxImmediate, 1)}x bet (before free spins and jackpots) |`);
  if (spec.freeSpins) out.push(`| Loose bound on one free-spin session | ${num(a.maxFreeSessionBound, 0)}x bet (cap x multiplier x best spin) |`);
  out.push('');
  out.push('## Base game vs bonus round');
  out.push('');
  out.push('| | RTP | Share |');
  out.push('|---|---:|---:|');
  out.push(`| Base game (${spec.mode} pays + scatter pays) | ${pct(a.split.baseGame, 3)} | ${pct(a.split.baseGame / a.rtp, 1)} |`);
  if (spec.freeSpins || spec.bonus) out.push(`| Bonus round (${[spec.freeSpins && 'free spins', spec.bonus && 'wheel credits'].filter(Boolean).join(' + ')}) | ${pct(a.split.bonusRound, 3)} | ${pct(a.split.bonusRound / a.rtp, 1)} |`);
  if (a.jackpots.length) out.push(`| Jackpots (${a.jackpots.map((j) => j.id).join(', ')}) | ${pct(a.split.progressives, 3)} | ${pct(a.split.progressives / a.rtp, 1)} |`);
  out.push(`| **Total** | **${pct(a.split.total, 3)}** | 100% |`);
  out.push('');
  out.push('## Where the return comes from');
  out.push('');
  out.push('| Component | RTP | Share |');
  out.push('|---|---:|---:|');
  const rows = [['Line / ways / cluster pays', a.components.lines], ['Scatter pays', a.components.scatter], ['Free spins', a.components.freeSpins], ['Bonus wheel credits', a.components.wheelCredits]];
  for (const [id, v] of Object.entries(a.components.wheelJackpots)) rows.push([`Wheel jackpot ${id}`, v]);
  for (const [id, v] of Object.entries(a.components.spinJackpots)) rows.push([`Per-spin jackpot ${id}`, v]);
  for (const [name, v] of rows) if (v > 0) out.push(`| ${name} | ${pct(v, 3)} | ${pct(v / a.rtp, 1)} |`);
  out.push(`| **Total** | **${pct(a.rtp, 3)}** | 100% |`);
  if (a.jackpots.length) {
    out.push('');
    out.push('## Jackpots');
    out.push('');
    out.push('| Jackpot | Feeds from | Odds per bet spin | Seed | Mean payout | RTP | Bet-funded | House-funded seed | Opens at bet |');
    out.push('|---|---|---:|---:|---:|---:|---:|---:|---:|');
    for (const j of a.jackpots) {
      out.push(`| ${j.id}${j.fixed ? ' (fixed odds)' : ''} | ${j.via} | 1 in ${oneIn(j.p)} | ${j.seed} cr (${num(j.seed / a.betCredits, 1)}x) | ${num(j.meanPayoutBets, 1)}x bet | ${pct(j.rtp, 3)} | ${pct(j.betFunded, 3)} | ${pct(j.houseFunded, 3)} | ${j.eligibleFromBet}x |`);
    }
    out.push('');
    out.push('A meter starts at its seed, grows by its contribution on every bet spin and resets when it hits; its size at a hit is `seed + contribution x G` with G the spins since the last hit (geometric, mean 1/p). Mean payout = seed + contribution / p. These are standalone meters (one machine), not linked.');
  }
  out.push('');
  out.push('## Win distribution (base spin: line pays + scatter pays, before free spins and jackpots)');
  out.push('');
  out.push('| Win | Probability | 1 in |');
  out.push('|---|---:|---:|');
  for (const r of a.histogram) if (r.p > 0) out.push(`| ${r.label} | ${pct(r.p, 4)} | ${oneIn(r.p)} |`);
  out.push('');
  out.push('## Bankroll needed');
  out.push('');
  out.push('Normal approximation of the spin-by-spin net result (mean -(1-RTP) bets, std dev above). Wins here are heavy-tailed, so read these as a floor, not a guarantee.');
  out.push('');
  out.push('| Spins | Bankroll for 95% | Bankroll for 99% |');
  out.push('|---:|---:|---:|');
  for (const c of a.confidence) out.push(`| ${c.spins.toLocaleString('en-US')} | ${num(c.bankroll95, 1)} bets | ${num(c.bankroll99, 1)} bets |`);
  out.push('');
  out.push('## Return by bet level');
  out.push('');
  out.push('| Bet (x base) | RTP | Jackpots open |');
  out.push('|---:|---:|---|');
  for (const b of a.perBet) out.push(`| ${b.bet} | ${pct(b.rtp, 3)} | ${b.eligible.join(', ') || '-'} |`);
  if (spec.scatter) {
    out.push('');
    out.push('## Scatter count distribution');
    out.push('');
    out.push('| Scatters | Probability | 1 in |');
    out.push('|---:|---:|---:|');
    for (const [n, p] of Object.entries(a.scatterDistribution)) if (p > 0) out.push(`| ${n} | ${pct(p, 4)} | ${oneIn(p)} |`);
  }
  if (spec.tuning) {
    out.push('');
    out.push('## Tuning record');
    out.push('');
    out.push(`Target ${pct(spec.tuning.target, 2)} +/- ${pct(spec.tuning.tolerance, 3)}; reached ${pct(spec.tuning.rtp, 4)} in ${spec.tuning.moves} integer moves (deterministic greedy descent on the exact mean).`);
    out.push('');
    out.push('| Move | Times | RTP after |');
    out.push('|---|---:|---:|');
    for (const s of spec.tuning.steps) out.push(`| ${s.move} | ${s.times} | ${pct(s.after, 4)} |`);
  }
  if (emitted) {
    out.push('');
    out.push('## Table data and random bytes');
    out.push('');
    out.push(`Emitted to \`src/generated/${spec.id}.8bs\`: **${emitted.dataBytes} bytes** in the program image.`);
    out.push('');
    out.push('| Table | Elements | Bytes |');
    out.push('|---|---:|---:|');
    for (const t of emitted.tables) out.push(`| \`${t.name}\` | ${t.length} x ${t.type} | ${t.bytes} |`);
    out.push('');
    out.push(`Random bytes: **${emitted.plan.perBaseSpin}** per base spin${emitted.plan.conditional.length ? `, plus ${emitted.plan.conditional.map((c) => `${c.bytes} for the wheel (only when ${c.when})`).join(', ')}` : ''}; **${emitted.plan.perFreeSpin}** per free spin.`);
    out.push('');
    out.push('| Order | Draw | Bytes | Meaning |');
    out.push('|---:|---|---:|---|');
    emitted.plan.items.forEach((i, n) => out.push(`| ${n + 1} | ${i.name} | ${i.bytes} | ${i.use} |`));
    for (const c of emitted.plan.conditional) out.push(`| then | ${c.name} (if ${c.when}) | ${c.bytes} | ${c.use} |`);
  }
  out.push('');
  return out.join('\n');
}
