// Prototype data for the X16 sprite-reel lab (docs/reel-size.md, route "VERA sprites"):
//   node tools/size/gen-x16.mjs
// Each symbol's 48x48 master PNG is set into the middle of a 64x64 VERA sprite (4 bpp, left pixel
// in the high nibble, palette index 0 = clear) so a reel's sprites sit on a 48-pixel pitch and
// overlap by their clear margins. The palette is the C64's sixteen colours, which is also the
// X16's first sixteen, so index n means colour n and black (0) is transparent.
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTheme } from '../tiles/src/theme.mjs';
import { MACHINES, nearest } from '../tiles/src/palettes.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PALETTE = MACHINES.cx16.palette;
const ALLOWED = Array.from({ length: 15 }, (_, i) => i + 1);

const rows = (values, per = 32) => values.map((v, i) => (i % per === 0 ? '\n    ' : '') + v).join(', ').replace(/, \n/g, ',\n');

const LABS = [
  { theme: 'classic', lab: 'proto-x16-3x3', game: 'classic3x3', reels: 3, rows: 3, x0: 216, top: 160, titleRow: 5, panelRow: 48, title: 'SPRITE REELS 3X3' },
  { theme: 'classic', lab: 'proto-x16-3x3-2x', game: 'classic3x3', reels: 3, rows: 3, x0: 64, top: 40, titleRow: 1, panelRow: 25, title: 'SPRITE REELS 3X3 AT 2X', scaled: 1 },
  { theme: 'cosmic', lab: 'proto-x16-5x5', game: 'grid5x5', reels: 5, rows: 5, x0: 152, top: 104, titleRow: 2, panelRow: 52, title: 'SPRITE REELS 5X5' },
];
const template = readFileSync(join(ROOT, 'tools', 'size', 'x16-lab.template.8bs'), 'utf8');
for (const { theme, lab, game, reels, rows: rowCount, x0, top, titleRow, panelRow, title, scaled = 0 } of LABS) {
  const t = await loadTheme(theme);
  const bytes = [];
  for (const s of t.symbols) {
    const { width, height, rgba } = s.img;
    const pixel = (x, y) => {
      const sx = x - 8, sy = y - 8;
      if (sx < 0 || sy < 0 || sx >= width || sy >= height) return 0;
      const o = (sy * width + sx) * 4;
      if (rgba[o + 3] < 128) return 0;
      return nearest(PALETTE, [rgba[o], rgba[o + 1], rgba[o + 2]], ALLOWED);
    };
    for (let y = 0; y < 64; y += 1) for (let x = 0; x < 64; x += 2) bytes.push((pixel(x, y) << 4) | pixel(x + 1, y));
  }
  const palette = [];
  for (let i = 0; i < 16; i += 1) {
    const [r, g, b] = PALETTE[i];
    palette.push(((g >> 4) << 4) | (b >> 4), r >> 4); // VERA: GB then 0R
  }
  const out = `// GENERATED by tools/size/gen-x16.mjs from assets/themes/${theme}/ — do not edit.
// ${t.symbols.length} symbols of 64x64 4bpp (2,048 bytes each; the 48x48 master sits at 8,8) and the 16-colour palette.
export const SYMBOL_COUNT: utinyint = ${t.symbols.length};
export const SYMBOL_BYTES: usmallint = 2048;
export const TOTAL_BYTES: usmallint = ${bytes.length};
export const PALETTE: array<utinyint, 32> = [${rows(palette, 16)}
];
export const SYMBOLS: array<utinyint, ${bytes.length}> = [${rows(bytes, 32)}
];
`;
  const dir = join(ROOT, 'src', 'labs', lab);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'data.8bs'), out);
  const main = template
    .replaceAll('{{LAB}}', lab).replaceAll('{{GAME}}', game).replaceAll('{{REELS_PLUS}}', String(rowCount + 1))
    .replaceAll('{{SCALED}}', String(scaled)).replaceAll('{{X0}}', String(x0)).replaceAll('{{TOP}}', String(top)).replaceAll('{{TITLE_COL}}', String(x0 / 8 - 2))
    .replaceAll('{{TITLE_ROW}}', String(titleRow)).replaceAll('{{PANEL_ROW}}', String(panelRow)).replaceAll('{{TITLE}}', title);
  writeFileSync(join(dir, 'main.8bs'), main);
  console.log(`${lab}/data.8bs  ${t.symbols.map((s) => s.id).join(' ')}  ${bytes.length} bytes`);
}
