// Prototype data for the PET / VIC-20 bigger-reel labs (docs/reel-size.md, route "bigger quadrant symbols"):
//   node tools/size/gen-quad.mjs
// A symbol is S x S character cells, each a 2x2 picture from the ROM's quadrant blocks, so 2S x 2S
// pseudo-pixels (S = 6: 12x12, 48x48 screen pixels). The reel is redrawn as it scrolls one pseudo-pixel
// row (4 pixels) at a time, and a display cell takes two consecutive pseudo-pixel rows, so the screen
// code of every display cell is one of three precomputed tables and a redraw is one read and one
// write per cell:
//   C0[symbol][k][c]       the window's pairs start on an even row: rows 2k, 2k+1 of the symbol
//   C1[symbol][k][c]       they start on an odd row: rows 2k+1, 2k+2 (k < S-1)
//   CX[symbol][next][c]    the odd pair that straddles two symbols: the last row of one, the first of the next
//   K[symbol][k][c]        the ink of the symbol cell (VIC-20 only)
import { writeFileSync, mkdirSync, readFileSync, copyFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTheme } from '../tiles/src/theme.mjs';
import { resample, QUAD_CODE, toPixelSymbol } from '../tiles/src/convert.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const rows = (values, per = 24) => values.map((v, i) => (i % per === 0 ? '\n    ' : '') + v).join(', ').replace(/, \n/g, ',\n');

const LABS = [
  { theme: 'classic', lab: 'proto-quad-3x3', game: 'classic3x3', S: 6, reels: 3, rowsShown: 3, topRow: 2, titleRow: 0, doneRow: 24, title: 'QUADRANT REELS 3X3' },
  { theme: 'cosmic', lab: 'proto-quad-5x5', game: 'grid5x5', S: 4, reels: 5, rowsShown: 5, topRow: 1, titleRow: 0, doneRow: 24, title: 'QUADRANT REELS 5X5' },
];

const shared = join(ROOT, 'src', 'labs', 'proto-quad-shared');
mkdirSync(shared, { recursive: true });
for (const f of readdirSync(join(ROOT, 'tools', 'size', 'quad-shared'))) copyFileSync(join(ROOT, 'tools', 'size', 'quad-shared', f), join(shared, f));
const template = readFileSync(join(ROOT, 'tools', 'size', 'quad-lab.template.8bs'), 'utf8');
for (const { theme, lab, game, S, reels, rowsShown, topRow, titleRow, doneRow, title } of LABS) {
  const t = await loadTheme(theme);
  const P = 2 * S;
  const bitmaps = t.symbols.map((s) => {
    const r = resample(s.img, P, P);
    return Array.from({ length: P }, (_, y) => Array.from({ length: P }, (_, x) => (r.cover[y * P + x] >= 0.5 ? 1 : 0)));
  });
  const code = (a, b, c) => QUAD_CODE[(a[2 * c] << 3) | (a[2 * c + 1] << 2) | (b[2 * c] << 1) | b[2 * c + 1]];
  const n = t.symbols.length;
  const C0 = [], C1 = [], CX = [], K = [];
  for (let s = 0; s < n; s += 1) {
    for (let k = 0; k < S; k += 1) for (let c = 0; c < S; c += 1) C0.push(code(bitmaps[s][2 * k], bitmaps[s][2 * k + 1], c));
    for (let k = 0; k < S - 1; k += 1) for (let c = 0; c < S; c += 1) C1.push(code(bitmaps[s][2 * k + 1], bitmaps[s][2 * k + 2], c));
  }
  for (let s = 0; s < n; s += 1) for (let u = 0; u < n; u += 1) for (let c = 0; c < S; c += 1) CX.push(code(bitmaps[s][P - 1], bitmaps[u][0], c));
  for (let s = 0; s < n; s += 1) {
    const px = toPixelSymbol(t.symbols[s].img, 'vic20', S, S);
    for (let k = 0; k < S * S; k += 1) K.push(px.colors[k] & 7);
  }
  const out = `// GENERATED by tools/size/gen-quad.mjs from assets/themes/${theme}/ — do not edit.
// ${n} symbols of ${S}x${S} cells = ${P}x${P} pseudo-pixels (${P * 4}x${P * 4} screen pixels), the ROM's 2x2 block glyphs.
// Index arithmetic stays under 256 on purpose: the 6502 backends compute a utinyint product in 8 bits.
export const S: utinyint = ${S};
export const NSYM: utinyint = ${n};
export const C0: array<utinyint, ${C0.length}> = [${rows(C0)}
];
export const C1: array<utinyint, ${C1.length}> = [${rows(C1)}
];
export const CX: array<utinyint, ${CX.length}> = [${rows(CX)}
];
export const K: array<utinyint, ${K.length}> = [${rows(K)}
];
`;
  const dir = join(ROOT, 'src', 'labs', lab);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'data.8bs'), out);
  const width = reels * (S + 1) + 1;
  const main = template
    .replaceAll('{{LAB}}', lab).replaceAll('{{GAME}}', game).replaceAll('{{THEME}}', theme).replaceAll('{{S}}', String(S)).replaceAll('{{P}}', String(P))
    .replaceAll('{{PIXELS}}', String(P * 4)).replaceAll('{{REELS}}', String(reels)).replaceAll('{{SHOWN}}', String(rowsShown)).replaceAll('{{TOPROW}}', String(topRow))
    .replaceAll('{{WIDTH}}', String(width)).replaceAll('{{CELLS_PER_REEL}}', String(rowsShown * S * S)).replaceAll('{{CELLS_ALL}}', String(reels * rowsShown * S * S))
    .replaceAll('{{TITLE_ROW}}', String(titleRow)).replaceAll('{{TITLE}}', title).replaceAll('{{DONE_ROW}}', String(doneRow));
  writeFileSync(join(dir, 'main.8bs'), main);
  console.log(`${lab}: ${n} symbols, S=${S}, C0 ${C0.length} C1 ${C1.length} CX ${CX.length} K ${K.length} = ${C0.length + C1.length + CX.length} B screen codes (+${K.length} B inks)`);
}
